### ISSUE TITLE
Tests fail with recent DataStructures

### ISSUE THREAD

**Issue by tkelman** [ararslan/Extern.jl#1]
started failing about a month ago, ref http://pkg.julialang.org/detail/Extern.html

**Comment by ararslan** [comment]
Ah, I forgot about this one. I should probably just deprecate it; I don't think anyone is using it, nor should they because it's kind of garbage. What do you think, fix on 0.5, upper bound the Julia version at 0.6-?

**Comment by tkelman** [comment]
maybe upper bound to 0.6 release so it won't break yet but won't be installable by people who use that release of julia

**Comment by ararslan** [comment]
I can't reproduce the test failure locally...

**Comment by ararslan** [comment]
Actually I can if I use `Pkg.test("Extern")` but not if I run the test code manually at the REPL. Weird.

**Comment by ararslan** [comment]
Oh, I see the problem.
